---
- hosts: redis
  sudo: yes
  tasks:
    - name: download redis
      get_url: url=http://download.redis.io/releases/redis-3.0.5.tar.gz dest=/tmp

    - name: tar redis
      unarchive: copy=no src=/tmp/redis-3.0.5.tar.gz dest=/tmp

    - name: make install redis
      command: make install
      args:
          chdir: /tmp/redis-3.0.5/

    - name: remove redis
      shell: rm -rf /tmp/redis-*

    - name: copy redis deploy file(debug)
      copy: src=redis_deploy dest=/tmp

    # - name: git clone redis deploy file
    #   git: repo=https://github.wdf.sap.corp/i319433/redis_deploy.git dest=/tmp/redis_deploy update=yes force=yes

    - name: add redis deploy script execute permission
      file: path=/tmp/redis_deploy state=directory recurse=yes mode="a+x"

    - name: copy redis service script to remote
      template: src={{ item.src }} dest=/etc/init.d/{{ item.dest }} mode="a+x"
      with_items:
          - {src: 'redis_6379.j2', dest: 'redis_6379'}
          - {src: 'redis_sentinel.j2', dest: 'redis_sentinel'}

- hosts: master
  sudo: yes
  tasks:
    - name: start master service
      command: env TYPE=MASTER MASTERIP={{ hostvars['master-node']['ansible_eth0']['ipv4']['address'] }} PASSWORD={{ redis_password }} ./deploy_redis.sh
      args:
        chdir: /tmp/redis_deploy/deploy

- hosts: slave
  sudo: yes
  tasks:
    - name: start slave service
      command: env TYPE=SLAVE MASTERIP={{ hostvars['master-node']['ansible_eth0']['ipv4']['address'] }} PASSWORD={{ redis_password }} ./deploy_redis.sh
      args:
        chdir: /tmp/redis_deploy/deploy
