---
- hosts: redis
  remote_user: root
  tasks:
    - name: download redis
      get_url: url=http://download.redis.io/releases/redis-3.0.5.tar.gz dest=/tmp

    - name: tar redis
      unarchive: copy=no src=/tmp/redis-3.0.5.tar.gz dest=/tmp

    - name: make install redis
      command: make install
      sudo: yes
      args:
          chdir: /tmp/redis-3.0.5/

    - name: remove redis
      shell: rm -rf /tmp/redis-*
      sudo: yes

    - name: git clone redis deploy
      git: repo=https://github.wdf.sap.corp/i319433/redis_deploy.git dest=/tmp/redis_deploy update=yes force=yes

    - name: add redis deploy script execute permission
      file: path=/tmp/redis_deploy state=directory recurse=yes mode="a+x"

- hosts: master
  remote_user: root
  tasks:
    - name: start master service
      command: env TYPE=MASTER MASTERIP={{ hostvars['master-node']['ansible_eth0']['ipv4']['address'] }} PASSWORD={{ redis_password }} ./deploy_redis.sh
      args:
        chdir: /tmp/redis_deploy/deploy
      sudo: yes

- hosts: slave
  remote_user: root
  tasks:
    - name: start slave service
      command: env TYPE=SLAVE MASTERIP={{ hostvars['master-node']['ansible_eth0']['ipv4']['address'] }} PASSWORD={{ redis_password }} ./deploy_redis.sh
      args:
        chdir: /tmp/redis_deploy/deploy
      sudo: yes
